#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-251226"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "92eaed8a27ab4b1ba24c5bebb53a7962" }
]

[assets]
directory = "./public"
